name: Build Image from Repo

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'ARM architecture: armv6l/aarch64'
        required: true
      version:
        description: 'HyperHDR version, for example 21.0.0.0'
        required: true
      tagCustomPiOS:
        description: 'Optional tag of CustomPiOS'
        default: ''

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      HYPERHDR_DEB: https://github.com/anshsharma240/HyperHDR/releases/download/v${{ github.event.inputs.version }}/HyperHDR-${{ github.event.inputs.version }}-Linux-${{ github.event.inputs.architecture }}.deb

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            coreutils \
            p7zip-full \
            qemu-user-static \
            xz-utils \
            python3-pip \
            jq \
            git \
            rsync \
            wget \
            curl
            
        pip3 install GitPython    

      - name: Checkout CustomPiOS
        uses: actions/checkout@v4
        with:
          repository: guysoft/CustomPiOS
          ref: ${{ github.event.inputs.tagCustomPiOS }}
          path: CustomPiOS

      - name: Prepare HyperHDR module
        run: |
          cd CustomPiOS
          sudo bash -x src/make_custom_pi_os HyperHDR
          sudo chown -R runner:runner HyperHDR

      - name: Fix arm64 Bullseye boot mount path
        if: github.event.inputs.architecture == 'aarch64'
        run: |
          echo 'export BASE_BOOT_MOUNT_PATH=boot' >> CustomPiOS/src/variants/raspios_lite_arm64/config
          echo 'Patched variant config:'
          cat CustomPiOS/src/variants/raspios_lite_arm64/config

      - name: Download Raspbian Image (32-bits)
        if: github.event.inputs.architecture != 'aarch64'
        run: |
          mkdir -p CustomPiOS/HyperHDR/src/image
          cd CustomPiOS/HyperHDR/src/image
          wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2023-05-03/2023-05-03-raspios-bullseye-armhf-lite.img.xz'
          echo "workspace_dir=CustomPiOS/HyperHDR/src/workspace" >> $GITHUB_ENV
          echo "workspace_variant=" >> $GITHUB_ENV

      - name: Download Raspbian Image (64-bits)
        if: github.event.inputs.architecture == 'aarch64'
        run: |
          mkdir -p CustomPiOS/HyperHDR/src/image-raspios_lite_arm64
          cd CustomPiOS/HyperHDR/src/image-raspios_lite_arm64
          wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-05-03/2023-05-03-raspios-bullseye-arm64-lite.img.xz'
          echo "workspace_dir=CustomPiOS/HyperHDR/src/workspace-raspios_lite_arm64" >> $GITHUB_ENV
          echo "workspace_variant=raspios_lite_arm64" >> $GITHUB_ENV

      - name: Update HyperHDR modules
        run: |
          cd CustomPiOS/HyperHDR/src
          {
            echo 'export DIST_NAME=HyperHDR'
            echo 'export DIST_VERSION=${{ github.event.inputs.version }}'
            echo 'export MODULES="base(network,hyperhdr)"'
            echo 'export RPI_IMAGER_NAME="${DIST_NAME} version ${DIST_VERSION}"'
            echo 'export RPI_IMAGER_DESCRIPTION="A Raspberry Pi distribution for ambient lighting. Ships HyperHDR out-of-the-box."'
            echo 'export RPI_IMAGER_ICON="https://github.com/anshsharma240/HyperHDR/blob/master/resources/icons/hyperhdr-icon-32px.png"'
            echo 'export BASE_IMAGE_ENLARGEROOT=2000'
            echo 'export BASE_IMAGE_RESIZEROOT=200'
          } > config

          cd modules/hyperhdr
          cat > start_chroot_script <<'EOF'
          #!/usr/bin/env bash
          set -ex
          source /common.sh

          type -p curl >/dev/null || apt install -y curl
          curl -fsSL https://anshsharma240.github.io/hyperhdr.public.apt.gpg.key | dd of=/usr/share/keyrings/hyperhdr.public.apt.gpg.key
          chmod go+r /usr/share/keyrings/hyperhdr.public.apt.gpg.key
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hyperhdr.public.apt.gpg.key] https://anshsharma240.github.io $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hyperhdr.list > /dev/null
          apt update
          apt install --only-upgrade -y udev
          apt install -y hyperhdr

          touch /boot/ssh
          echo -n 'pi:' > /boot/userconf
          echo 'raspberry' | openssl passwd -6 -stdin >> /boot/userconf

          echo "HyperHDR" > /etc/hostname
          sed -i 's/raspberrypi/HyperHDR/' /etc/hosts
          systemctl -q enable hyperhdr@pi.service

          sed -i 's/^#dtparam=spi=on.*/dtparam=spi=on/' /boot/config.txt
          sed -i 's/^#hdmi_force_hotplug=1.*/hdmi_force_hotplug=1/' /boot/config.txt
          EOF

          chmod +x start_chroot_script

      - name: Build HyperHDR Raspbian Image
        run: |
          sudo modprobe loop
          cd CustomPiOS/HyperHDR
          sudo bash -x src/build_dist ${{ env.workspace_variant }}

      - name: Copy output
        id: copy
        run: |
          IMAGE=SD-card-image-${{ github.event.inputs.version }}-${{ github.event.inputs.architecture }}
          cp ${{ env.workspace_dir }}/*.img $IMAGE.img
          xz -v9 $IMAGE.img
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.copy.outputs.image }}
          path: ${{ steps.copy.outputs.image }}.img.xz
